############# English navigation ##############

# main menu
[[main]]
name = "ğŸ  Home"
url = "/"
weight = 1

[[main]]
name = "ğŸ“ Blog"
url = "blog/"
weight = 2

[[main]]
weight = 3
name = "ğŸ“š Categories"
url = "categories/"

[[main]]
name = "ğŸ™‹ğŸ»â€â™‚ï¸ About"
url = "about/"
weight = 4

# footer menu

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 1

